name: Semgrep
on:
  pull_request:
  push:
    branches:
      - main

  schedule:
    # Set to run everyday at 12am SGT = 4pm UTC
    - cron: "0 16 * * *"

jobs:
  semgrep:
    runs-on: ci
    container:
      image: returntocorp/semgrep
      options: --dns 8.8.8.8

    steps:
      - name: Cleanup folder
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run semgrep
        run: semgrep ci
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: p/default p/security-audit p/owasp-top-ten p/ci p/jwt p/xss p/secrets p/r2c-bug-scan p/javascript p/clientside-js
